= Parameters

The parent key for all of the following parameters is `csi_driver_nfs`.

== `namespace`

[horizontal]
type:: string
default:: `syn-csi-driver-nfs`

The namespace in which to deploy this component.

== `charts`

[horizontal]
type:: object
default:: https://github.com/projectsyn/component-csi-driver-nfs/blob/master/class/defaults.yml[See `class/defaults.yml`]

The Helm chart for the NFS CSI driver.

== `images`

[horizontal]
type:: object
default:: https://github.com/projectsyn/component-csi-driver-nfs/blob/master/class/defaults.yml[See `class/defaults.yml`]

The container image used by the NFS CSI driver.

TIP: Helm value `image.baseRepo` allows overriding the container image registry for all images that aren't defined in this parameter.

== `controller`

[horizontal]
type:: object

Configurations for the NFS CSI controller.

=== `controller.serviceAccountName`

[horizontal]
type:: string
default:: `csi-nfs-controller-sa`

The service account name for the NFS CSI controller.
This parameter is passed to the Helm chart and used by the component to configure a `RoleBinding` to grant the controller access to the `privileged` SCC on OpenShift.

== `node`

[horizontal]
type:: object

Configurations for the NFS CSI node daemonset.

=== `node.serviceAccountName`

[horizontal]
type:: string
default:: `csi-nfs-node-sa`

The service account name for the NFS CSI node daemonset.
This parameter is passed to the Helm chart and used by the component to configure a `RoleBinding` to grant the node daemonset access to the `privileged` SCC on OpenShift.

== `helmValues`

[horizontal]
type:: object
default:: https://github.com/projectsyn/component-csi-driver-nfs/blob/master/class/defaults.yml[See `class/defaults.yml]

The Helm values that are used to render the Helm chart.

== Example

[source,yaml]
----
namespace: example-namespace
----
